package dk.statsbiblioteket.medieplatform.newspaper.manualQA;

import dk.statsbiblioteket.medieplatform.autonomous.Batch;
import dk.statsbiblioteket.medieplatform.autonomous.ResultCollector;
import dk.statsbiblioteket.medieplatform.autonomous.iterator.common.AttributeParsingEvent;
import dk.statsbiblioteket.medieplatform.newspaper.manualQA.flagging.FlaggingCollector;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;

public class HistogramAverageHandlerTest {
    @Test
    public void testHandleAttributeGood() throws Exception {
        ResultCollector resultCollector = new ResultCollector("blah", "blah");
        Batch batch = new Batch("40000");
        FlaggingCollector flaggingCollector = new FlaggingCollector(batch, null, "0.1-SNAPSHOT");
        HistogramAverageHandler histogramHandler = new HistogramAverageHandler(
                resultCollector, flaggingCollector, batch);
        AttributeParsingEvent event = createAttributeEvent("B400022028252-RT1/400022028252-08/1795-12-20-01/adresseavisen1759-1795-12-20-01-0079.jp2.histogram.xml","<histogram xmlns=\"http://www.statsbiblioteket.dk/avisdigitalisering/histogram/1/0/\">\n" +
                                                           "    <colorScheme>\n" +
                                                           "        <colorSpace>\n" +
                                                           "            Grayscale\n" +
                                                           "        </colorSpace>\n" +
                                                           "        <colorDepth>\n" +
                                                           "            8 bits\n" +
                                                           "        </colorDepth>\n" +
                                                           "    </colorScheme>\n" +
                                                           "\n" +
                                                           "    <colors>\n" +
                                                           "        <color>\n" +
                                                           "            <code>0</code>\n" +
                                                           "            <count>3324</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>1</code>\n" +
                                                           "            <count>7691</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>2</code>\n" +
                                                           "            <count>104168</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>3</code>\n" +
                                                           "            <count>10522</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>4</code>\n" +
                                                           "            <count>9585</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>5</code>\n" +
                                                           "            <count>8549</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>6</code>\n" +
                                                           "            <count>8673</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>7</code>\n" +
                                                           "            <count>8928</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>8</code>\n" +
                                                           "            <count>9819</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>9</code>\n" +
                                                           "            <count>10865</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>10</code>\n" +
                                                           "            <count>11960</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>11</code>\n" +
                                                           "            <count>13803</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>12</code>\n" +
                                                           "            <count>15455</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>13</code>\n" +
                                                           "            <count>17832</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>14</code>\n" +
                                                           "            <count>19815</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>15</code>\n" +
                                                           "            <count>22290</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>16</code>\n" +
                                                           "            <count>24973</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>17</code>\n" +
                                                           "            <count>27915</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>18</code>\n" +
                                                           "            <count>31033</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>19</code>\n" +
                                                           "            <count>33681</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>20</code>\n" +
                                                           "            <count>36459</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>21</code>\n" +
                                                           "            <count>39032</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>22</code>\n" +
                                                           "            <count>41431</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>23</code>\n" +
                                                           "            <count>43008</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>24</code>\n" +
                                                           "            <count>44855</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>25</code>\n" +
                                                           "            <count>45694</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>26</code>\n" +
                                                           "            <count>46886</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>27</code>\n" +
                                                           "            <count>47675</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>28</code>\n" +
                                                           "            <count>48464</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>29</code>\n" +
                                                           "            <count>49443</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>30</code>\n" +
                                                           "            <count>49759</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>31</code>\n" +
                                                           "            <count>49715</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>32</code>\n" +
                                                           "            <count>49910</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>33</code>\n" +
                                                           "            <count>49754</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>34</code>\n" +
                                                           "            <count>49347</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>35</code>\n" +
                                                           "            <count>48628</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>36</code>\n" +
                                                           "            <count>48669</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>37</code>\n" +
                                                           "            <count>48172</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>38</code>\n" +
                                                           "            <count>47580</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>39</code>\n" +
                                                           "            <count>46532</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>40</code>\n" +
                                                           "            <count>46066</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>41</code>\n" +
                                                           "            <count>45204</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>42</code>\n" +
                                                           "            <count>44642</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>43</code>\n" +
                                                           "            <count>43623</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>44</code>\n" +
                                                           "            <count>42737</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>45</code>\n" +
                                                           "            <count>41980</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>46</code>\n" +
                                                           "            <count>42120</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>47</code>\n" +
                                                           "            <count>41795</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>48</code>\n" +
                                                           "            <count>41657</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>49</code>\n" +
                                                           "            <count>41167</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>50</code>\n" +
                                                           "            <count>40971</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>51</code>\n" +
                                                           "            <count>41152</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>52</code>\n" +
                                                           "            <count>41310</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>53</code>\n" +
                                                           "            <count>41171</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>54</code>\n" +
                                                           "            <count>41510</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>55</code>\n" +
                                                           "            <count>41982</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>56</code>\n" +
                                                           "            <count>41833</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>57</code>\n" +
                                                           "            <count>42209</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>58</code>\n" +
                                                           "            <count>42276</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>59</code>\n" +
                                                           "            <count>43097</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>60</code>\n" +
                                                           "            <count>43062</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>61</code>\n" +
                                                           "            <count>43815</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>62</code>\n" +
                                                           "            <count>44376</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>63</code>\n" +
                                                           "            <count>44749</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>64</code>\n" +
                                                           "            <count>45244</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>65</code>\n" +
                                                           "            <count>45665</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>66</code>\n" +
                                                           "            <count>46285</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>67</code>\n" +
                                                           "            <count>46920</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>68</code>\n" +
                                                           "            <count>47047</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>69</code>\n" +
                                                           "            <count>47343</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>70</code>\n" +
                                                           "            <count>48329</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>71</code>\n" +
                                                           "            <count>48944</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>72</code>\n" +
                                                           "            <count>49069</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>73</code>\n" +
                                                           "            <count>49912</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>74</code>\n" +
                                                           "            <count>50650</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>75</code>\n" +
                                                           "            <count>51238</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>76</code>\n" +
                                                           "            <count>51214</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>77</code>\n" +
                                                           "            <count>52021</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>78</code>\n" +
                                                           "            <count>52368</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>79</code>\n" +
                                                           "            <count>52292</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>80</code>\n" +
                                                           "            <count>52780</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>81</code>\n" +
                                                           "            <count>53567</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>82</code>\n" +
                                                           "            <count>53616</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>83</code>\n" +
                                                           "            <count>54004</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>84</code>\n" +
                                                           "            <count>54467</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>85</code>\n" +
                                                           "            <count>54719</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>86</code>\n" +
                                                           "            <count>54999</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>87</code>\n" +
                                                           "            <count>55231</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>88</code>\n" +
                                                           "            <count>55859</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>89</code>\n" +
                                                           "            <count>56518</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>90</code>\n" +
                                                           "            <count>56445</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>91</code>\n" +
                                                           "            <count>56984</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>92</code>\n" +
                                                           "            <count>57061</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>93</code>\n" +
                                                           "            <count>57646</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>94</code>\n" +
                                                           "            <count>57751</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>95</code>\n" +
                                                           "            <count>57730</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>96</code>\n" +
                                                           "            <count>58916</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>97</code>\n" +
                                                           "            <count>59269</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>98</code>\n" +
                                                           "            <count>59610</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>99</code>\n" +
                                                           "            <count>59710</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>100</code>\n" +
                                                           "            <count>60226</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>101</code>\n" +
                                                           "            <count>60784</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>102</code>\n" +
                                                           "            <count>61726</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>103</code>\n" +
                                                           "            <count>62041</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>104</code>\n" +
                                                           "            <count>62510</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>105</code>\n" +
                                                           "            <count>62815</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>106</code>\n" +
                                                           "            <count>63072</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>107</code>\n" +
                                                           "            <count>63886</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>108</code>\n" +
                                                           "            <count>64058</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>109</code>\n" +
                                                           "            <count>64423</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>110</code>\n" +
                                                           "            <count>64528</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>111</code>\n" +
                                                           "            <count>64800</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>112</code>\n" +
                                                           "            <count>64525</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>113</code>\n" +
                                                           "            <count>64306</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>114</code>\n" +
                                                           "            <count>64739</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>115</code>\n" +
                                                           "            <count>64695</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>116</code>\n" +
                                                           "            <count>63919</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>117</code>\n" +
                                                           "            <count>64716</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>118</code>\n" +
                                                           "            <count>64197</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>119</code>\n" +
                                                           "            <count>63989</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>120</code>\n" +
                                                           "            <count>63663</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>121</code>\n" +
                                                           "            <count>63449</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>122</code>\n" +
                                                           "            <count>63271</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>123</code>\n" +
                                                           "            <count>63411</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>124</code>\n" +
                                                           "            <count>62997</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>125</code>\n" +
                                                           "            <count>62712</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>126</code>\n" +
                                                           "            <count>62699</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>127</code>\n" +
                                                           "            <count>62824</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>128</code>\n" +
                                                           "            <count>62613</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>129</code>\n" +
                                                           "            <count>61282</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>130</code>\n" +
                                                           "            <count>61344</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>131</code>\n" +
                                                           "            <count>60981</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>132</code>\n" +
                                                           "            <count>61195</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>133</code>\n" +
                                                           "            <count>60615</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>134</code>\n" +
                                                           "            <count>61429</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>135</code>\n" +
                                                           "            <count>60832</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>136</code>\n" +
                                                           "            <count>60778</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>137</code>\n" +
                                                           "            <count>59904</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>138</code>\n" +
                                                           "            <count>59984</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>139</code>\n" +
                                                           "            <count>59840</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>140</code>\n" +
                                                           "            <count>59655</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>141</code>\n" +
                                                           "            <count>59863</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>142</code>\n" +
                                                           "            <count>58847</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>143</code>\n" +
                                                           "            <count>58760</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>144</code>\n" +
                                                           "            <count>58743</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>145</code>\n" +
                                                           "            <count>58827</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>146</code>\n" +
                                                           "            <count>58020</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>147</code>\n" +
                                                           "            <count>58066</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>148</code>\n" +
                                                           "            <count>58141</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>149</code>\n" +
                                                           "            <count>58272</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>150</code>\n" +
                                                           "            <count>57511</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>151</code>\n" +
                                                           "            <count>57129</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>152</code>\n" +
                                                           "            <count>57397</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>153</code>\n" +
                                                           "            <count>57079</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>154</code>\n" +
                                                           "            <count>56957</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>155</code>\n" +
                                                           "            <count>56290</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>156</code>\n" +
                                                           "            <count>56706</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>157</code>\n" +
                                                           "            <count>56575</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>158</code>\n" +
                                                           "            <count>56321</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>159</code>\n" +
                                                           "            <count>56583</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>160</code>\n" +
                                                           "            <count>56305</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>161</code>\n" +
                                                           "            <count>56039</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>162</code>\n" +
                                                           "            <count>55965</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>163</code>\n" +
                                                           "            <count>55628</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>164</code>\n" +
                                                           "            <count>55496</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>165</code>\n" +
                                                           "            <count>55660</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>166</code>\n" +
                                                           "            <count>55095</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>167</code>\n" +
                                                           "            <count>54421</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>168</code>\n" +
                                                           "            <count>54078</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>169</code>\n" +
                                                           "            <count>53057</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>170</code>\n" +
                                                           "            <count>53016</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>171</code>\n" +
                                                           "            <count>52734</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>172</code>\n" +
                                                           "            <count>52309</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>173</code>\n" +
                                                           "            <count>52098</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>174</code>\n" +
                                                           "            <count>51606</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>175</code>\n" +
                                                           "            <count>51390</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>176</code>\n" +
                                                           "            <count>50829</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>177</code>\n" +
                                                           "            <count>50182</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>178</code>\n" +
                                                           "            <count>49864</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>179</code>\n" +
                                                           "            <count>49682</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>180</code>\n" +
                                                           "            <count>49622</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>181</code>\n" +
                                                           "            <count>48952</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>182</code>\n" +
                                                           "            <count>49050</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>183</code>\n" +
                                                           "            <count>48307</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>184</code>\n" +
                                                           "            <count>48929</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>185</code>\n" +
                                                           "            <count>48931</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>186</code>\n" +
                                                           "            <count>48639</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>187</code>\n" +
                                                           "            <count>48902</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>188</code>\n" +
                                                           "            <count>49290</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>189</code>\n" +
                                                           "            <count>49522</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>190</code>\n" +
                                                           "            <count>49814</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>191</code>\n" +
                                                           "            <count>50427</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>192</code>\n" +
                                                           "            <count>50920</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>193</code>\n" +
                                                           "            <count>51140</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>194</code>\n" +
                                                           "            <count>52395</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>195</code>\n" +
                                                           "            <count>52708</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>196</code>\n" +
                                                           "            <count>53557</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>197</code>\n" +
                                                           "            <count>54624</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>198</code>\n" +
                                                           "            <count>55726</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>199</code>\n" +
                                                           "            <count>57259</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>200</code>\n" +
                                                           "            <count>58719</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>201</code>\n" +
                                                           "            <count>60455</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>202</code>\n" +
                                                           "            <count>61892</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>203</code>\n" +
                                                           "            <count>63880</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>204</code>\n" +
                                                           "            <count>65545</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>205</code>\n" +
                                                           "            <count>68099</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>206</code>\n" +
                                                           "            <count>70853</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>207</code>\n" +
                                                           "            <count>73263</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>208</code>\n" +
                                                           "            <count>77179</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>209</code>\n" +
                                                           "            <count>80080</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>210</code>\n" +
                                                           "            <count>83202</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>211</code>\n" +
                                                           "            <count>87167</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>212</code>\n" +
                                                           "            <count>90806</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>213</code>\n" +
                                                           "            <count>94379</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>214</code>\n" +
                                                           "            <count>97730</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>215</code>\n" +
                                                           "            <count>101682</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>216</code>\n" +
                                                           "            <count>105430</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>217</code>\n" +
                                                           "            <count>108204</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>218</code>\n" +
                                                           "            <count>110723</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>219</code>\n" +
                                                           "            <count>112999</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>220</code>\n" +
                                                           "            <count>114665</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>221</code>\n" +
                                                           "            <count>114530</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>222</code>\n" +
                                                           "            <count>114436</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>223</code>\n" +
                                                           "            <count>112632</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>224</code>\n" +
                                                           "            <count>111248</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>225</code>\n" +
                                                           "            <count>110189</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>226</code>\n" +
                                                           "            <count>110941</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>227</code>\n" +
                                                           "            <count>112422</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>228</code>\n" +
                                                           "            <count>117391</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>229</code>\n" +
                                                           "            <count>125852</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>230</code>\n" +
                                                           "            <count>137392</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>231</code>\n" +
                                                           "            <count>154366</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>232</code>\n" +
                                                           "            <count>177146</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>233</code>\n" +
                                                           "            <count>210015</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>234</code>\n" +
                                                           "            <count>251836</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>235</code>\n" +
                                                           "            <count>301160</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>236</code>\n" +
                                                           "            <count>364557</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>237</code>\n" +
                                                           "            <count>449481</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>238</code>\n" +
                                                           "            <count>557429</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>239</code>\n" +
                                                           "            <count>692275</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>240</code>\n" +
                                                           "            <count>900980</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>241</code>\n" +
                                                           "            <count>1176520</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>242</code>\n" +
                                                           "            <count>1479790</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>243</code>\n" +
                                                           "            <count>1794129</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>244</code>\n" +
                                                           "            <count>2174465</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>245</code>\n" +
                                                           "            <count>2505533</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>246</code>\n" +
                                                           "            <count>2544286</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>247</code>\n" +
                                                           "            <count>2122334</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>248</code>\n" +
                                                           "            <count>1277166</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>249</code>\n" +
                                                           "            <count>444093</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>250</code>\n" +
                                                           "            <count>53732</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>251</code>\n" +
                                                           "            <count>1746</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>252</code>\n" +
                                                           "            <count>56</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>253</code>\n" +
                                                           "            <count>3</count>\n" +
                                                           "        </color>\n" +
                                                           "        <color>\n" +
                                                           "            <code>254</code>\n" +
                                                           "            <count>0</count>\n" +
                                                           "        </color>\n" +
                                                           "    </colors>\n" +
                                                           "</histogram>\n");
        histogramHandler.handleAttribute(event);
        Assert.assertFalse(flaggingCollector.hasFlags(),flaggingCollector.toReport());
    }

    private AttributeParsingEvent createAttributeEvent(String name, final String contents){
        return new AttributeParsingEvent(name) {
            @Override
            public InputStream getData() throws IOException {
                return new ByteArrayInputStream(contents.getBytes());

            }

            @Override
            public String getChecksum() throws IOException {
                return null;
            }
        };
    }
}
