#!/usr/bin/env bash

/usr/bin/gnuplot <<EOF

# Output in png format, size width,height
set terminal png size 1800,900

set output "output-plot.png"

set title "Histogram plot"
set ylabel "y-value"
set xlabel "x-value"

# Set the style of data plots to "show points and draw lines between them"
set style data linespoints

# Place legend top left instead of top right
set key left top

# Plot column 1 and 2 from data file, assumed separated by whitespace
plot "histogram.dat" using 1:2 title "DigiTV Ritzau"

EOF

